# Site settings
title: GLVisualize
email: sdanisch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GLVisualize Documentation
  This is great!
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  SimonDanisch

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter: pygments
